#ifndef DEBUG_COMMAND_H
#define DEBUG_COMMAND_H

#include "cmsis_os.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    DEBUG_CMD_NONE = 0,
    DEBUG_CMD_ENABLE,
    DEBUG_CMD_DISABLE,
    DEBUG_CMD_START,
    DEBUG_CMD_STOP,
    DEBUG_CMD_SET_CURRENT,
    DEBUG_CMD_SET_SPEED,
    DEBUG_CMD_SET_ANGLE,
    DEBUG_CMD_SET_STEP_ANGLE,
    DEBUG_CMD_SET_LOW_SPEED,
    DEBUG_CMD_SET_SPEED_PID,
    DEBUG_CMD_SET_ANGLE_PID,
    DEBUG_CMD_SET_CURRENT_LIMIT,
    DEBUG_CMD_SET_ANGLE_LIMIT,
    DEBUG_CMD_DISABLE_ANGLE_LIMIT,
    DEBUG_CMD_SET_ANGLE_RATE_LIMIT,
    DEBUG_CMD_SET_ANGLE_CMD_DEADBAND,
    DEBUG_CMD_BALL_ENABLE,
    DEBUG_CMD_BALL_DISABLE,
    DEBUG_CMD_BALL_SET_TARGET,
    DEBUG_CMD_BALL_START_SEQUENCE,
    DEBUG_CMD_BALL_START_TASK,
    DEBUG_CMD_BALL_INITIALIZE_TASK,
    DEBUG_CMD_BALL_STOP_TASK,
    DEBUG_CMD_BALL_SET_BALANCE_ANGLE,
    DEBUG_CMD_BALL_SET_GAINS,
    DEBUG_CMD_BALL_SET_FEEDFORWARD,
    DEBUG_CMD_BALL_SET_FEEDFORWARD_SPLIT,
    DEBUG_CMD_BALL_SET_VISION_WEIGHT,
    DEBUG_CMD_BALL_SET_D_WEIGHT,
    DEBUG_CMD_BALL_SET_BRAKE_P,
    DEBUG_CMD_BALL_SET_BRAKE_P_LONG,
    DEBUG_CMD_BALL_SET_BRAKE_P_SPEED,
    DEBUG_CMD_BALL_SET_BRAKE_P_NEGATIVE_MAX,
    DEBUG_CMD_BALL_SET_TERMINAL_BRAKE_GATE,
    DEBUG_CMD_BALL_SET_TERMINAL_PUSH,
    DEBUG_CMD_BALL_SET_TERMINAL_PUSH_POSITIVE,
    DEBUG_CMD_BALL_SET_TERMINAL_PUSH_NEGATIVE,
    DEBUG_CMD_BALL_SET_ANGLE_LIMIT,
    DEBUG_CMD_BALL_SET_DEADBAND,
    DEBUG_CMD_BALL_SET_RATE,
    DEBUG_CMD_VISION_SET_FILTER,
    DEBUG_CMD_VISION_SET_MEASUREMENT_DEADBAND,
    DEBUG_CMD_VISION_SET_FILTER_LIMITS,
    DEBUG_CMD_VISION_SET_VELOCITY,
    DEBUG_CMD_VISION_SET_PREDICTION,
    DEBUG_CMD_VISION_SET_AB_CORRECTION_LIMIT,
    DEBUG_CMD_SET_ZERO_POINT,
    DEBUG_CMD_CLEAR_ZERO_POINT
} DebugCommandId_t;

typedef struct {
    DebugCommandId_t id;
    float arg1;
    float arg2;
    float arg3;
    float arg4;
} DebugCommand_t;

extern osMessageQueueId_t DebugCommandHandle;

#ifdef __cplusplus
}
#endif

#endif


